# Generated by Django 5.2.8 on 2025-11-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2',
            name='headimg',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user2',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user2',
            name='openid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
