# Generated by Django 5.2.8 on 2025-11-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkapp', '0002_user2_headimg_user2_nickname_user2_openid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='openid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
